config/routes.rb
Thundercats::Application.routes.draw do
  get "orders/index"
  get "store/index"
  devise_for :users
  resources :customers
  post "store/add_cart"

  resources :products

  post "products/assign_category", :as => :assign_category

  get "products-by-category/:category_id" => "store#index", as: :products_by_category

   root 'store#index'

  

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_one :order
	validates_presence_of :name, :phone, :email, :address1, :address2, :city, :state, :zip
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        current_cart = session[:cart]
        order = Order.new
        order.customer_id = @customer.id

        sub_total = Cart.calculate_cart_total(current_cart)
        order.sub_total = sub_total
        order.sale_tax = sub_total * Order::CURRENT_SALES_TAX

        order.grand_total = order.sub_total + order.sale_tax     
        order.save

        current_cart.each do |key, item|
          line_item = LineItem.new
          line_item.product_id = key
          line_item.quantity = item[0]
          line_item.unit_price = item[2]
          line_item.line_item_total = line_item.quantity * line_item.unit_price
          line_item.order_id = order.id
          line_item.save
        end

        #clear the session / cart
        session.clear

        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @customer }
      else
        format.html { render action: 'new' }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :phone, :email, :address1, :address2, :city, :state, :zip)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :address1 %><br>
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label :address2 %><br>
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Listing customers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Address1</th>
      <th>Address2</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.phone %></td>
        <td><%= customer.email %></td>
        <td><%= customer.address1 %></td>
        <td><%= customer.address2 %></td>
        <td><%= customer.city %></td>
        <td><%= customer.state %></td>
        <td><%= customer.zip %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>Enter Personal Information</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Thank you for your business</h2>
  <h4>Your order has been received.</h4>

    <% order = @customer.order %>

    <% if ! order.blank? %> 
      <% order.line_items.each do |line_item| %>
        <%= line_item.quantity %>
        <%= line_item.product.name %>
        <%= number_to_currency (line_item.unit_price) %>
        <br> 
      <% end %>
      Sub Total: <%= number_to_currency order.sub_total %> <br>
      Sales Tax: <%= number_to_currency order.sale_tax %> <br>
      Grand Total: <%= number_to_currency order.grand_total %> <br>
    
    <% else %>
      Your cart is empty
    <%end%>
<hr>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @customer.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<p>
  <strong>Address1:</strong>
  <%= @customer.address1 %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @customer.address2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @customer.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @customer.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @customer.zip %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>