config/routes.rb
Thundercats::Application.routes.draw do
  get "orders/index"
  get "store/index"
  devise_for :users
  resources :customers
  post "store/add_cart"

  resources :products

  post "products/assign_category", :as => :assign_category

  get "products-by-category/:category_id" => "store#index", as: :products_by_category

   root 'store#index'

  

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :line_items
	has_many :product_categories, :dependent => :destroy
	has_many :categories, :through => :product_categories

	validates_presence_of :name, :unit_price, :description, :quantity, :sku, :brand, :model_num
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  def assign_category
    my_params = params.require(:product_category).permit(:product_id, :category_id)
    @product_category = ProductCategory.new(my_params)
    
    if @product_category.save
      redirect_to edit_product_path(@product_category.product_id)
    else
      @product = Product.find(@product_category.product_id)
      render action: 'edit'
    end
  end


  # GET /products/1/edit
  def edit
    @product_category = ProductCategory.new
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        @product_category = ProductCategory.new
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :unit_price, :description, :quantity, :sku, :brand, :model_num)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :unit_price %><br>
    <%= f.text_field :unit_price %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :sku %><br>
    <%= f.text_field :sku %>
  </div>
  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :model_num %><br>
    <%= f.text_field :model_num %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>


<div style ="float:left; width:40%">
<%= render 'form' %>
</div>

<div style = "float:left; width:40%">
	<h3>Add Category</h3>
	<%= form_for(@product_category, url: assign_category_path) do |f| %>
		  <% if @product_category.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@product_category.errors.count, "error") %> prohibited this product from being saved:</h2>

	      <ul>
	      <% @product_category.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
	<%= f.hidden_field :product_id, value: @product.id %>
	<%= f.select :category_id, Category.all.map {|cat| [cat.name,cat.id]}%>
	<%= f.submit "Add Assign Category" %>
	<%end%>

	<h3>Categories</h3>
	<% @product.categories.each do |cat|%>
		<%= cat.name %>
	<% end %>



</div>

<div style="clear:both;"> </div>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Unit price</th>
      <th>Description</th>
      <th>Quantity</th>
      <th>Sku</th>
      <th>Brand</th>
      <th>Model num</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.unit_price %></td>
        <td><%= product.description %></td>
        <td><%= product.quantity %></td>
        <td><%= product.sku %></td>
        <td><%= product.brand %></td>
        <td><%= product.model_num %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Unit price:</strong>
  <%= @product.unit_price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Sku:</strong>
  <%= @product.sku %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand %>
</p>

<p>
  <strong>Model num:</strong>
  <%= @product.model_num %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>